title: Victor Lin
permalink: ':title/'
url: "https://victorlin.github.io"

# Author Settings
author: Victor Lin
facebook: VictorLinMashups
github: victorlin
linkedin: victor-lin
youtube: VictorLin
google_scholar: DrzHirYAAAAJ

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "blog/page/:num"

collections:
  mashups:
    output: true

sass:
    sass_dir: assets/css/scss

analytics: UA-109654720-1

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
